feat: add tonemapping effect
Tresjs/post-processing pull request #148
Opened 2024-11-29 11:50 UTC by damienmontastier

This component introduces the `ToneMapping` effect, which provides an abstraction for various tone mapping algorithms from the [`pmndrs/postprocessing`](https://github.com/pmndrs/postprocessing) package. The `<ToneMapping>` effect is specifically designed to improve the visual rendering of HDR content by mapping high-range brightness values to a displayable range, thus enhancing luminance and color balance in the scene.

- Fixes potential issues with incorrect colors when `EffectComposer` is added by applying tone mapping manually as an effect.
- Easy to set up — simply include it in your `<EffectComposer>` pipeline.
- Multiple tone mapping modes and options for fine-tuning luminance are available.
- Fully supports different blend functions for enhanced visual styles.

For more details, see [ToneMapping](https://pmndrs.github.io/postprocessing/public/docs/class/src/effects/ToneMappingEffect.js~ToneMappingEffect.html) on [pmndrs/postprocessing](https://github.com/pmndrs/postprocessing).

___

Local Playground — `pnpm run playground`

Local Documentation — `pnpm run docs:dev`

___

@alvarosabu @Tinoooo

2024-12-01 22:09 UTC, Tinoooo requested changes
Thank you @damienmontastier for your PR. Very helpful!

2024-12-01 22:09 UTC, Tinoooo commented on src/core/pmndrs/ToneMapping.vue
> +    [() => props.minLuminance, 'minLuminance'],
**suggestion:** I think this has to be like so:
```suggestion
    [() => props.minLuminance, 'adaptiveLuminanceMaterial.minLuminance'],
```

`minLuminance` is not a property of `effect.value`. These paths are used to update the effect when the props change. So we need the exact location of the property.

2024-12-01 22:09 UTC, Tinoooo commented on src/core/pmndrs/ToneMapping.vue
> +    [() => props.mode, 'mode'],
**suggestion:** You can omit the seperate watcher like so:

```suggestion
makePropWatchers(
  [
    [() => props.blendFunction, 'blendMode.blendFunction'],
    [() => props.mode, 'mode'],
```

2024-12-01 22:21 UTC, Tinoooo commented on docs/guide/pmndrs/tonemapping.md
> +```vue{2,4,7-8,32-36}
**suggestion:** While I like to have a full example on the page, I think it is better to stay uniform with the other effects and only show the usage.

2025-01-03 14:15 UTC, alvarosabu commented
Hi @damienmontastier, we will need to update this PR (and probably all the others) to adapt to the breaking change introduced in v2 https://github.com/Tresjs/post-processing/releases/tag/2.0.0 

Mostly adding the correct Suffix to the effects if they are from the [pmndrs/postprocessing](https://github.com/pmndrs/postprocessing) package. Let me know if you have any questions or we can help you out.

Sorry about this

2025-01-03 18:31 UTC, damienmontastier commented on docs/guide/pmndrs/tonemapping.md
modified at next commit

2025-01-03 18:32 UTC, damienmontastier commented on src/core/pmndrs/ToneMapping.vue
> +    mode: ToneMappingMode.AGX,
modified at next commit

2025-01-03 18:36 UTC, damienmontastier commented on src/core/pmndrs/ToneMapping.vue
> +    [() => props.minLuminance, 'minLuminance'],
Exactly! Small mistake on my part! Modified at next commit

2025-01-03 18:40 UTC, damienmontastier commented on src/core/pmndrs/ToneMapping.vue
> +    [() => props.mode, 'mode'],
Modified at next commit

2025-01-03 18:46 UTC, damienmontastier commented on docs/guide/pmndrs/tonemapping.md
> +```vue{2,4,7-8,32-36}
I think it's a shame that we don't produce slightly advanced demos to present concrete use cases.

What do you think @alvarosabu ?

2025-01-03 18:47 UTC, damienmontastier commented
@alvarosabu I've just adapted the ToneMapping component for V2 of the package ✌️

2025-01-06 19:57 UTC, Tinoooo commented on src/core/pmndrs/ToneMapping.vue
> +    mode: ToneMappingMode.AGX,
The defaults are still in there.

2025-01-06 20:02 UTC, Tinoooo commented on docs/guide/pmndrs/tonemapping.md
> +```vue{2,4,7-8,32-36}
I agree. The downside would be, that there can be increased maintenance effort in case the parameters of the effects change upstream.

I'm fine as long as the docs are uniform.

2025-01-07 21:33 UTC, damienmontastier commented on src/core/pmndrs/ToneMapping.vue
> +    mode: ToneMappingMode.AGX,
it's done

2025-01-10 20:14 UTC, Tinoooo requested changes

2025-01-10 20:14 UTC, Tinoooo commented on playground-nuxt/.nuxt/app.config.mjs
**suggestion:** please omit the changes in the folder `playground-nuxt` from this MR.

2025-01-10 21:42 UTC, damienmontastier commented on playground-nuxt/.nuxt/app.config.mjs
fix in the last commit!

2025-01-10 21:46 UTC, Tinoooo commented on docs/guide/pmndrs/tonemapping.md
> +```vue{2,4,7-8,32-36}
Let's leave it the way it is for now and decide later. The advantage of having the effect outweighs the non-uniform docs.

2025-01-10 21:48 UTC, Tinoooo approved these changes

2025-01-10 21:48 UTC, merged

2025-01-11 12:07 UTC, alvarosabu commented on docs/guide/pmndrs/tonemapping.md
> +```vue{2,4,7-8,32-36}
Hi guys, I agree with Tino here, from a documentation perspective, it's always better to stay simple and focus on the usage of the effect. For advance demos we can always use the Cookbook https://docs.tresjs.org/cookbook/