fix: 58 postprocessing breaks on nuxt
Tresjs/post-processing pull request #69
Opened 2023-10-26 15:30 UTC by alvarosabu

Closes #58

2023-10-27 15:40 UTC, Tinoooo requested changes

2023-10-27 15:40 UTC, Tinoooo commented on src/core/EffectComposer.vue
> +  if (props.enabled) initEffectComposer()
```suggestion
  if (sizes.height.value && sizes.width.value && props.enabled) {
    initEffectComposer()
    stop()
  }
```

Caution: I did not test the suggestion 😄

2023-10-28 09:26 UTC, alvarosabu commented
Tested your approach and all good, should we merge it then?

2023-10-28 09:30 UTC, Tinoooo commented
> Tested your approach and all good, should we merge it then?

Yes 💪
I'll do it.

2023-10-28 09:30 UTC, Tinoooo approved these changes

2023-10-28 09:31 UTC, merged